language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

addons:
  postgresql: "9.6"
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

php:
  - 7.0
  - 7.1

env:
  matrix:
    - DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
    - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE

matrix:
  include:
    - php: 5.6
      env: DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 5.6
      env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
